version: '3.8'
services:
  webpage:
    container_name: webpage
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - "80:80"
    networks:
      - student-list-networks
    depends_on:
      - api
    volumes:
      - ./website:/var/www/html

  api:
    container_name: api
    image: api-etudiants
    #ports:
      #- "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - student-list-networks

networks:
  student-list-networks:
    driver: bridge
    name: student-list-networks